### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by Xerios** [PlasticApps/PlasticTween#1]
Thanks for creating this, I was hoping someone would do a better job than my half-arsed implementation. Seems like you went much further than me 👍 

Mind if I link you on my project? https://github.com/Xerios/ECS-Tween
I doubt I'll ever finish/update mine, it was more of a educational test rather than a fully fledged tweening system.

**Comment by PlasticApps** [comment]
Hi Xerios, thanks for your comment and open issue (:. And Yes, of course you can do it.

**Comment by Xerios** [comment]
Heh, it was pretty unnecessary to link mine :)

I just added you to my site [unitylist.com](unitylist.com), make sure to add a picture/logo or something and you'll get those stars and forks in no time ;)
